### ISSUE TITLE
Needed help for bytes pattern in Python3

### ISSUE THREAD

**Issue by rsmekala** [pyparsing/pyparsing#100]
I needed some help with the below pattern.

Pattern:
```
{{[{W:(0123...) [. W:(0123...)]... Suppress:(":")}] Suppress:("<") W:(0123...) Suppress:(">") W:(ABCD...,abcd...) W:(0123...) Combine:({W:(0123...) ":" W:(0123...) ":" W:(0123...)}) W:(ABCD...) W:(ABCD...) [{Suppress:("[") W:(0123...) Suppress:("]")}] Suppress:(":") Re:('.*') StringEnd} | Suppress:(LineEnd)}
```

It works fine in Python 2 environment, but in Python 3 environment it generates the following exception. I do understand, that it is caused due to the fundamental difference in str implementation between Python2 and Python3.

Can you help me with a pattern that can match bytes input or string input alike without converting the input from bytes to string or vice-versa ??

### Logs
```
Traceback (most recent call last):
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/salt/engines/junos_syslog.py", line 173, in parse
    parsed = self.__pattern.parseString(line)
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 1818, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 3902, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 3735, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 4458, in parseImpl
    loc, tokens = self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 3735, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 4098, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 3735, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 1566, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rsmekala/test/venv/lib/python3.7/site-packages/pyparsing.py", line 2933, in parseImpl
    result = self.re.match(instring,loc)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by ptmcg** [comment]
At the moment, pyparsing has many internal bits that assume the input string will be str type. In Py2, this would silently treat bytes like str, or str like unicode, but as you have found, Py3 is more particular. At this time, you'll need to decode your bytes string into a str before passing to parseString.
