### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

### ISSUE THREAD

**Issue by 5j9** [pyparsing/pyparsing#12]
```
...Python37\lib\site-packages\pkg_resources\_vendor\pyparsing.py:943: DeprecationWarning: Using or
importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  collections.MutableMapping.register(ParseResults)
...Python37\lib\site-packages\pkg_resources\_vendor\pyparsing.py:3226: DeprecationWarning: Using or
 importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  elif isinstance( exprs, collections.Iterable ):
```

**Comment by 5j9** [comment]
Already reported at https://sourceforge.net/p/pyparsing/bugs/106/ .

**Comment by ptmcg** [comment]
Thanks - I will get 2.2.1 out later this summer, and I'll include the resolution for this in that release

**Comment by jaraco** [comment]
Summer's almost over. Perhaps this issue shouldn't be closed until the issue is fixed?

**Comment by ptmcg** [comment]
Sorry, I will wait until the release to close.

**Comment by paulmcg-iio** [comment]
2.2.1 released this morning with this fix - please confirm that this is resolved, then I will close.

**Comment by jaraco** [comment]
Confirmed fixed:

```
~ $ rwt pyparsing -- -W error -c 'import pyparsing'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyparsing.py", line 943, in <module>
    collections.MutableMapping.register(ParseResults)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 52, in __getattr__
    DeprecationWarning, stacklevel=2)
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
~ $ rwt git+https://github.com/pyparsing/pyparsing -- -W error -c 'import pyparsing'; echo no problem
Collecting git+https://github.com/pyparsing/pyparsing
  Cloning https://github.com/pyparsing/pyparsing to /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-z1cuizhd
Building wheels for collected packages: pyparsing
  Running setup.py bdist_wheel for pyparsing ... done
  Stored in directory: /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-ephem-wheel-cache-s3ngwn5q/wheels/42/78/51/cfe57a45666985b7b533be6944ad74616004c1eee0017d05b2
Successfully built pyparsing
Installing collected packages: pyparsing
Successfully installed pyparsing-2.2.1
no problem
```

**Comment by jaraco** [comment]
Also the released version:

```
~ $ rwt pyparsing==2.2.1 -- -W error -c 'import pyparsing'; echo no-problem
Collecting pyparsing==2.2.1
  Downloading https://files.pythonhosted.org/packages/42/47/e6d51aef3d0393f7d343592d63a73beee2a8d3d69c22b053e252c6cfacd5/pyparsing-2.2.1-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 173kB/s
Installing collected packages: pyparsing
Successfully installed pyparsing-2.2.1
no-problem
```
