### ISSUE TITLE
Sphinx error

### ISSUE THREAD

**Issue by egberts** [pyparsing/pyparsing#120]
Latest master tree (2.5.0a1), I cannot create the pyparsing document anymore.

```bash
pyparsing/docs$ make html
Running Sphinx v1.4.9

Configuration error:
There is a syntax error in your configuration file: invalid syntax (pyparsing.py, line 541)
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 1
```

Did I miss a step prior to performing that 'make html'?

**Comment by egberts** [comment]
Test run using `make -d html`:

```bash
pyparsing/docs$ make -d html
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Updating makefiles....
 Considering target file 'Makefile'.
  File 'Makefile' does not exist.
  Finished prerequisites of target file 'Makefile'.
 Must remake target 'Makefile'.
 Successfully remade target file 'Makefile'.
Updating goal targets....
Considering target file 'html'.
 Looking for an implicit rule for 'html'.
 Trying pattern rule with stem 'html'.
 Trying rule prerequisite 'Makefile'.
 Found an implicit rule for 'html'.
  Pruning file 'Makefile'.
 Finished prerequisites of target file 'html'.
 Prerequisite 'Makefile' of target 'html' does not exist.
Must remake target 'html'.
Putting child 0x562f64816cd0 (html) PID 16503 on the chain.
Live child 0x562f64816cd0 (html) PID 16503 
Running Sphinx v1.4.9

Configuration error:
There is a syntax error in your configuration file: invalid syntax (pyparsing.py, line 541)
Reaping losing child 0x562f64816cd0 PID 16503 
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 1
Removing child 0x562f64816cd0 PID 16503 from chain.
```

**Comment by egberts** [comment]
Commit is "2.5.0a1"

```bash
git log

commit fd82368c8ed6e29027db5b7d2040069ad2b13a16
Author: ptmcg <ptmcg@austin.rr.com>
Date:   Thu Aug 22 13:29:23 2019 -0500

    Additional problematic characters when generating re's in Word added to unit test
```

**Comment by egberts** [comment]
I'm confused to the terminology as to config syntax.  I had thought that sphinx-build is reading the conf.py for its config, yet it is reading `pyparsing.py` for whatever then spewing an error at `pyparsing.py:541` at https://github.com/pyparsing/pyparsing/blob/6a899ffd880d7937e6e8fd540552c65f945dce53/pyparsing.py#L541

Increased the verbosity of `sphinx-build`

```bash
pyparsing/docs$ sphinx-build -M html "." "_build" -v -v -v
Running Sphinx v1.4.9

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 137, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 289, in __init__
    raise ConfigError(CONFIG_SYNTAX_ERROR % err)
ConfigError: There is a syntax error in your configuration file: invalid syntax (pyparsing.py, line 541)

Configuration error:
There is a syntax error in your configuration file: invalid syntax (pyparsing.py, line 541)
```

If assuming that Sphinx rightfully is reading the pyparsing.py file, it would appear that the `sphinx-build` is choking on some esoteric Python syntax at line 541.

**Comment by egberts** [comment]
## Work around

Delete old configuration files:
```bash
cd pyparsing/
cd docs/
rm conf.py
rm index.rst
```
Recreate the configuration file:
```bash
sphinx-quickstart
# Answer mostly 'no's.
```
Then create the document
```
make html
firefox build/html/index.html
```

**Comment by egberts** [comment]
If you want to create a PDF file (for use on iPhone's iBook, before you execute `make latexpdf` on Debian, you'll probably want the following APT packages:

```
sudo -i
apt install latexmk texlive texlive-science texlive-formats-extra \
    texlive-fonts-recommended texlive-generic-extra

**Comment by egberts** [comment]
Might be better to create a HOWTO using `sphinx-quickstart` than to check-in a `conf.py` configuration file (which is version-dependent on Sphinx).

**Comment by egberts** [comment]
Excerpt:  Keep in mind that the file uses Python syntax for strings, numbers, lists and so on. The file is saved in UTF-8 by default, as indicated by the encoding declaration in the first line. If you use non-ASCII characters in any string value, you need to use Python Unicode strings (like project = u'Exposé').

Source: https://www.sphinx-doc.org/en/1.5/tutorial.html

**Comment by egberts** [comment]
## A Fix 
A real fix is to accommodate the Sphinx with an extra pair of parenthesis around the logic of line 541.

**Comment by egberts** [comment]
Might be far better to wait until Sphinx 1.5+ is stable with Python3;

Use Python2.7 for now.  (I was using Python 3.7).
