### ISSUE TITLE
(Caseless)?Keyword supposedly can be followed by punctuation but fails to digest a colon

### ISSUE THREAD

**Issue by metaperl** [pyparsing/pyparsing#201]
[The docs for Keyword and hence CaselessKeyword](https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html#basic-parserelement-subclasses) state:

> similar to Literal, but must be immediately followed by whitespace, punctuation, or other non-keyword characters;

However a colon is punctuation and the following grammar chokes at the colon:

```python
"""
Parse the signals from Olafemi Adeyemo's Telegram channel.
"""

sample_signal = """Opengates Forex Trade Signal Alert Services:

Symbol: EURNZD

Action: SELL

Entry: 1.83605

TakeProfit: 1.83386

StopLoss: 1.85217

Good Favor.
"""

import re
from pyparsing import Word, alphas, alphanums, CaselessKeyword, CaselessLiteral, Combine, Optional, Literal, nums
from pyparsing import Regex


header = Regex("Opengates.+Services:", flags=re.IGNORECASE)

trading_pair = Word(alphanums)*6
symbol = CaselessKeyword("Symbol:") + trading_pair

buy_or_sell = CaselessLiteral("buy") | CaselessLiteral("sell")
action = CaselessKeyword("Action") + buy_or_sell

point = Literal(".")
e = CaselessLiteral("E")
plusorminus = Literal("+") | Literal("-")
number = Word(nums)
integer = Combine(Optional(plusorminus) + number)
float_number = Combine(
    integer + Optional(point + Optional(number)) + Optional(e + integer)
)
entry = CaselessKeyword("Entry") + float_number
take_profit = CaselessKeyword("TakeProfit") + float_number
stop_loss = CaselessKeyword("StopLoss") + float_number

footer = Regex(".+", flags=re.IGNORECASE)

trade_signal = header + symbol + action + entry + take_profit + stop_loss + footer


if __name__ == '__main__':
    result = trade_signal.parseString(sample_signal)
    print(f"Result of parsing={result}")
```

**Comment by ptmcg** [comment]
Maybe I need to make that doc a little clearer. The Keyword and CaselessKeyword expression types don't _include_ the following punctuation or other non-keyword character, but they require that it be present to distinguish their behavior from Literal and CaselessLiteral.

Compare:
```
>>> import pyparsing as pp
>>> pp.Literal("if").parseString("ifonly")
(['if'], {})
```
with
```
>>> pp.Keyword("if").parseString("ifonly")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "F:\Paul\dev\pyparsing\gh\pyparsing\venv\lib\site-packages\pyparsing.py", line 1947, in parseString
    raise exc
  File "F:\Paul\dev\pyparsing\gh\pyparsing\venv\lib\site-packages\pyparsing.py", line 1937, in parseString
    loc, tokens = self._parse(instring, 0)
  File "F:\Paul\dev\pyparsing\gh\pyparsing\venv\lib\site-packages\pyparsing.py", line 1681, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "F:\Paul\dev\pyparsing\gh\pyparsing\venv\lib\site-packages\pyparsing.py", line 2953, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected "if", found 'i'  (at char 0), (line:1, col:1)
```
(Hmm, that error message could be a little better.) The point is, the Keyword doesn't match because it is not a standalone word "if", but is followed immediately by "only". 

In your particular case, since you expect keywords to be followed by colons, you'll have to add the colon to the parser:
```
entry = CaselessKeyword("Entry") + ':' + float_number
take_profit = CaselessKeyword("TakeProfit") + ':' + float_number
stop_loss = CaselessKeyword("StopLoss") + ':' + float_number
```

When I have multiple similar expressions like this, I sometimes write a little local helper function:
```
def labeled_float(label):
    return CaselessKeyword(label) + Suppress(':') + float_number(label.lower())

entry = labeled_float("Entry")
take_profit = labeled_float("TakeProfit")
stop_loss = labeled_float("StopLoss")
```

**Comment by ptmcg** [comment]
Also check out `help(pyparsing.Keyword)`

**Comment by ptmcg** [comment]
I'm checking in changes for 3.0.0 for improved error messages
