### ISSUE TITLE
enablePackrat dont parse all text with parseAll=True

### ISSUE THREAD

**Issue by pikhovkin** [pyparsing/pyparsing#247]
pyparsing 3.0.0a2

Minimal code
```
from pyparsing import *

ParserElement.enablePackrat()

stmt = Forward()
indent_stack = [1]

block = indentedBlock(stmt, indent_stack)

CLASS = (Word(alphanums) + Suppress(':') + block)
FIELD = (Word(alphanums) + Suppress('=') + Word(nums) + Suppress(':') + block)
stmt <<= CLASS | FIELD | Keyword('pass')
parser = OneOrMore(stmt)
data='''
A:
    a=8:
        pass

B:
    b=8:
        pass
'''
parser.parseString(data, parseAll=True).pprint()
```

i get an error
```
Traceback (most recent call last):
  File "/.../minimal_code.py", line 23, in <module>
    parser.parseString(data, parseAll=True).pprint()
  File "/.../venv/lib/python3.6/site-packages/pyparsing/core.py", line 804, in parseString
    raise exc
  File "/.../venv/lib/python3.6/site-packages/pyparsing/core.py", line 2914, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.exceptions.ParseException: Expected end of text, found 'B'  (at char 27), (line:6, col:1)
```

Where am I wrong?

**Comment by pikhovkin** [comment]
@ptmcg do you have any ideas?

**Comment by ptmcg** [comment]
Packrat parsing and `indentedBlock` are not going to play well together. `indentedBlock` uses parse actions to update the indent stack, but packrat parsing will not recall parse actions for matches that it gets from its internal cache.

I am working on a reimplementation of `indentedBlock` as an `IndentedBlock` class, which should do better stack management and encapsulation of the expression and parsed results. But the interaction with the packrat cache will still very likely prevent both of them working together.

I'm sorry to have taken so long to respond, especially since the answer is essentially "you can't do that".  I'll update the docs to so indicate.

**Comment by pikhovkin** [comment]
@ptmcg 
I made a DSL like Python. But the pyparsing parses expressions with round brackets very long time (hours). That was the original problem.

**Comment by ptmcg** [comment]
I recently wrote a parser using the new IndentedBlock and with left-recursion enabled. LR also uses packrat parsing, so it is indicative to me that the new IndentedBlock class is more tolerant of packrat cacheing than the old (lowercase) indentedBlock helper. Please revisit using the latest 3.0.7 release.

**Comment by pikhovkin** [comment]
pyparsing 3.0.7

The code is the same.

Error
```bash
Traceback (most recent call last):
  File "/.../minimal_code.py", line 23, in <module>
    parser.parseString(data, parseAll=True).pprint()
  File "/.../venv/lib/python3.8/site-packages/pyparsing/core.py", line 1134, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found 'B'  (at char 27), (line:6, col:1)
```

**Comment by ptmcg** [comment]
Closing this as old - recent reimplementation of nested_expr and infix_notation may address these issues.
