### ISSUE TITLE
3.0.0: BytesWarning in _null_values comparison

### ISSUE THREAD

**Issue by The-Compiler** [pyparsing/pyparsing#271]
I recently started testing my project with development versions of all direct dependencies, and `--pre` installs of indirect dependencies. I also turn on Python's [byte warnings](https://docs.python.org/3/using/cmdline.html#cmdoption-b). This apparently causes pyparsing 3 to fail, via pytest/packaging.requirements:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File ".../site-packages/_pytest/config/__init__.py", line 188, in console_main
    code = main()
  File ".../site-packages/_pytest/config/__init__.py", line 146, in main
    config = _prepareconfig(args, plugins)
  File ".../site-packages/_pytest/config/__init__.py", line 325, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File ".../site-packages/pluggy/hooks.py", line 281, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File ".../site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".../site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: _multicall(
  File ".../site-packages/pluggy/callers.py", line 130, in _multicall
    gen.send(outcome)
  File ".../site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File ".../site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".../site-packages/pluggy/callers.py", line 114, in _multicall
    res = hook_impl.function(*args)
  File ".../site-packages/_pytest/config/__init__.py", line 1022, in pytest_cmdline_parse
    self.parse(args)
  File ".../site-packages/_pytest/config/__init__.py", line 1306, in parse
    self._preparse(args, addopts=addopts)
  File ".../site-packages/_pytest/config/__init__.py", line 1198, in _preparse
    self._validate_plugins()
  File ".../site-packages/_pytest/config/__init__.py", line 1265, in _validate_plugins
    from packaging.requirements import InvalidRequirement, Requirement
  File ".../site-packages/packaging/requirements.py", line 94, in <module>
    REQUIREMENT.parseString("x[]")
  File ".../site-packages/pyparsing/core.py", line 859, in parseString
    loc, tokens = self._parse(instring, 0)
  File ".../site-packages/pyparsing/core.py", line 631, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File ".../site-packages/pyparsing/core.py", line 3273, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File ".../site-packages/pyparsing/core.py", line 631, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File ".../site-packages/pyparsing/core.py", line 3474, in parseImpl
    ret = e._parse(
  File ".../site-packages/pyparsing/core.py", line 631, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File ".../site-packages/pyparsing/core.py", line 3251, in parseImpl
    loc, resultlist = self.exprs[0]._parse(
  File ".../site-packages/pyparsing/core.py", line 631, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File ".../site-packages/pyparsing/core.py", line 3251, in parseImpl
    loc, resultlist = self.exprs[0]._parse(
  File ".../site-packages/pyparsing/core.py", line 676, in _parseNoCache
    retTokens = ParseResults(
  File ".../site-packages/pyparsing/results.py", line 164, in __init__
    if toklist not in self._null_values:
BytesWarning: Comparison between bytes and int
```

I've printed the values, and they are `3` and `(None, b'', '', [], ())` - here's a more minimal reproducer of the underlying issue:

```pytb
$ python3 -bb -c "3 in (None, b'', '', [], ())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
BytesWarning: Comparison between bytes and int
```

due to:

```pytb
$ python3 -bb -c "3 == b''" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
BytesWarning: Comparison between bytes and int
```

A standalone example based on what `packaging` does:

```python
from pyparsing import (  # noqa: N817
    Combine,
    Literal as L,
    Optional,
    ParseException,
    Regex,
    Word,
    ZeroOrMore,
    originalTextFor,
    stringEnd,
    stringStart,
)
import string, re

ALPHANUM = Word(string.ascii_letters + string.digits)

LPAREN = L("(").suppress()
RPAREN = L(")").suppress()
COMMA = L(",").suppress()

NAME = ALPHANUM("name")

VERSION_PEP440 = Regex('x', re.VERBOSE | re.IGNORECASE)
VERSION_LEGACY = Regex('x', re.VERBOSE | re.IGNORECASE)

VERSION_ONE = VERSION_PEP440 ^ VERSION_LEGACY
VERSION_MANY = Combine(
    VERSION_ONE + ZeroOrMore(COMMA + VERSION_ONE), joinString=",", adjacent=False
)("_raw_spec")
_VERSION_SPEC = Optional(((LPAREN + VERSION_MANY + RPAREN) | VERSION_MANY))
_VERSION_SPEC.setParseAction(lambda s, l, t: t._raw_spec or "")

VERSION_SPEC = originalTextFor(_VERSION_SPEC)("specifier")
VERSION_SPEC.setParseAction(lambda s, l, t: t[1])

NAMED_REQUIREMENT = NAME + VERSION_SPEC

REQUIREMENT = stringStart + NAMED_REQUIREMENT + stringEnd
REQUIREMENT.parseString("x")
```

**Comment by The-Compiler** [comment]
This regressed in 3.0.0b1 - bisected to 7f68a2aa4386e8a075aabc92ca8b6582bcc25a42 ("minor perf changes").

**Comment by ptmcg** [comment]
Thanks so much for testing this out - I'll revert to prior logic.

**Comment by ptmcg** [comment]
I just removed the comparison with b"" as a possible null value. Thanks for running this pre-release version through this extra screen process.

**Comment by The-Compiler** [comment]
Thanks for the fix! I can confirm the git master is working fine for me.
