### ISSUE TITLE
Regression: delimitedList used to accept a string argument, but now fails with streamline() error

### ISSUE THREAD

**Issue by ptmcg** [pyparsing/pyparsing#331]
Trying to create a delimitedList with:

    a_list = delimited_list("A")

Gives this traceback:

```
Traceback (most recent call last):
  File "C:\Users\ptmcg\AppData\Roaming\JetBrains\PyCharm2021.2\scratches\issue_330.py", line 3, in <module>
    d = delimited_list('A', max=1000)
  File "C:\Users\ptmcg\dev\pyparsing\gh\pyparsing\pyparsing\helpers.py", line 42, in delimited_list
    expr=str(expr.streamline()),
AttributeError: 'str' object has no attribute 'streamline'
```

This used to work.

(Found while investigating #330)

**Comment by ptmcg** [comment]
Released in 3.0.6
