### ISSUE TITLE
Use string boundary check instead of IndexError.

### ISSUE THREAD

**Issue by guswns0528** [pyparsing/pyparsing#4]
When IndexError has thrown in user's parse action function, some parse elements consume it and, raise ParseError. It makes user confused.

```
number = Word(nums)
def number_action():
    raise IndexError
number.setParseAction(number_action)
symbol = Word('abcd', max=1)
expr = number | symbol
expr.parseString('1 + 2')
```

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    expr.parseString('1 + 2')
  File "/home/joon/.pyenv/versions/pypy2.7-5.8.0/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
ParseException: Expected {W:(0123...) | W:(abcd)} (at char 5), (line:1, col:6)
```

This shows what I say. There's a problem in number_action function, but MatchFirst consumes IndexError and raise ParseError. It makes user to debug grammar rules. Because pyparsing throws ParseError, not IndexError at number_action.

**Comment by guswns0528** [comment]
It seems good👍. This solution is more reasonable than I suggested.

**Comment by ptmcg** [comment]
Looking more closely into implementing this, my first pass uses "raise new_exception from other_exception", a syntax that is only valid in Python3 - gives a SyntaxError if I try this with python2. I can simulate "raise ... from ..." in a way that will not break under Py2, but the magic chaining between exceptions will only work when run using Py3. I hope that will be sufficient.

**Comment by ektestein** [comment]
I have the same problem.
My code example:
```py
from pyparsing import LineEnd, LineStart, Literal, SkipTo

incoming_text = '''
>>>
rsth
>>>
<<<

<<<

>>>
inea
>>>
<<<
>>>
<<<
'''

input_border = Literal('>>>')

input_block = LineStart() + input_border \
              + SkipTo(input_border, include=True).setResultsName('input_body')

output_border = Literal('<<<')
output_block = LineStart() + output_border + LineEnd() \
               - ~input_border \
               + SkipTo(output_border, include=True).setResultsName('output_body')

test_block = input_block + output_block

x = test_block.searchString(incoming_text)
```
and result of execution:
```py
C:\Users\ektestein\AppData\Local\Programs\Python\Python36\python.exe C:/Users/ektestein/.PyCharmCE2018.1/config/scratches/scratch_16.py
pyparsing.ParseException: Found unwanted token, ">>>" (at char 41), (line:13, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/ektestein/.PyCharmCE2018.1/config/scratches/scratch_16.py", line 31, in <module>
    x = test_block.searchString(incoming_text)
  File "C:\Users\ektestein\AppData\Local\Programs\Python\Python36\lib\site-packages\pyparsing.py", line 1964, in searchString
    raise exc
  File "C:\Users\ektestein\AppData\Local\Programs\Python\Python36\lib\site-packages\pyparsing.py", line 1958, in searchString
    return ParseResults([ t for t,s,e in self.scanString( instring, maxMatches ) ])
  File "C:\Users\ektestein\AppData\Local\Programs\Python\Python36\lib\site-packages\pyparsing.py", line 1958, in <listcomp>
    return ParseResults([ t for t,s,e in self.scanString( instring, maxMatches ) ])
  File "C:\Users\ektestein\AppData\Local\Programs\Python\Python36\lib\site-packages\pyparsing.py", line 1888, in scanString
    raise exc
  File "C:\Users\ektestein\AppData\Local\Programs\Python\Python36\lib\site-packages\pyparsing.py", line 1866, in scanString
    nextLoc,tokens = parseFn( instring, preloc, callPreParse=False )
  File "C:\Users\ektestein\AppData\Local\Programs\Python\Python36\lib\site-packages\pyparsing.py", line 1548, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\ektestein\AppData\Local\Programs\Python\Python36\lib\site-packages\pyparsing.py", line 3718, in parseImpl
    raise ParseSyntaxException._from_exception(pe)
pyparsing.ParseSyntaxException: Found unwanted token, ">>>" (at char 41), (line:13, col:1)

Process finished with exit code 1
```

**Comment by ptmcg** [comment]
I don't believe this is the same issue. The posted issue involves exceptions that are raised within parse actions. In your posted code, you are getting "Found unwanted token" because the `'>>>'` in the final output block is explicitly forbidden by the ` - ~input_border` expression in output_block. If you remove that (or remove the `>>>` in the last output block, your code will run successfully. Why did you think this was not working correctly?

**Comment by ektestein** [comment]
I expect that parser will throw me the first exception, that I'll be able
to catch. But it throws ParseSyntaxException that I can't catch (`except
BaseException` doesn't help)

Globally I want to find error (in example) and show it to user, but get
this exception. Do I something wrong, may be?

**Comment by ptmcg** [comment]
Try catching `pyparsing.ParseBaseException`.
