### ISSUE TITLE
Install from source fails using latest pip (22.1)

### ISSUE THREAD

**Issue by iknox-fa** [pyparsing/pyparsing#400]
Hi there!  It appears that pip 22.1 breaks source installs of pyparsing.  
I've tested this with python 3.8 - 3.10 and pyparsing 3.0.7 - 3.0.9 and all have returned the same result seen below.  

TBH my python packaging-fu isn't strong enough to tell if this is a pip bug or a pyparsing bug, but I thought it worth filing an issue.

<details>
<summary>Click to view error</summary>

```
pip install -v --no-deps --no-binary :all: --ignore-installed ~/Downloads/pyparsing-pyparsing_3.0.9
Using pip 22.1 from /Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip (python 3.10)
Processing /Users/iknox/Downloads/pyparsing-pyparsing_3.0.9
  Running command pip subprocess to install build dependencies
  Collecting flit_core<4,>=3.2
    Using cached flit_core-3.7.1.tar.gz (40 kB)
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: flit_core
    Building wheel for flit_core (pyproject.toml): started
    Building wheel for flit_core (pyproject.toml): finished with status 'done'
    Created wheel for flit_core: filename=flit_core-3.7.1-py3-none-any.whl size=60195 sha256=ae546f54faee8b92a60ab2ee79511b6b694e55cba25351a1f30fdb5cbeda2aee
    Stored in directory: /Users/iknox/Library/Caches/pip/wheels/54/87/76/ea703765f904c482a43161ee927e47ca327bef7cb046b443a8
  Successfully built flit_core
  Installing collected packages: flit_core
  Successfully installed flit_core-3.7.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 340, in run
    requirement_set = resolver.resolve(
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 506, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 291, in __init__
    super().__init__(
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 421, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 490, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 57, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 45, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 114, in _install_build_reqs
    conflicting, missing = self.req.build_env.check_requirements(build_reqs)
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_internal/build_env.py", line 178, in check_requirements
    if req.marker is not None and not req.marker.evaluate():
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 304, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 234, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/Users/iknox/Projects/python-models/.direnv/python-3.10.0/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 215, in _get_env
    raise UndefinedEnvironmentName(
pip._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```

</details>

**Comment by ptmcg** [comment]
3.0.7 was the first release to replace setup.py with flit for building releases. That would be the place to start.

**Comment by ptmcg** [comment]
@mgorny - can you please look at this?

**Comment by mgorny** [comment]
Yeah, just wanted to say that it looks like a regression in pip 22.1. I would start by filing an issue there. Even if something was wrong with pyparsing or flit (I don't think it is), pip would rather "print" an error message rather than throwing an exception.

**Comment by mgorny** [comment]
Actually, it seems to be already fixed in pip's `main` branch. I can reproduce the error with 22.1 tag but main is good.

**Comment by r-f-g** [comment]
For me the installation failed with same error with pip 22.1 and fix was downgrade to pip 22.0.4.

The environment:
```bash
root@charmcraft-cloudsupport-6426229-0-0-amd64:~/project# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
root@charmcraft-cloudsupport-6426229-0-0-amd64:~/project# /root/parts/charm/build/staging-venv/bin/python --version
Python 3.8.10
root@charmcraft-cloudsupport-6426229-0-0-amd64:~/project# /root/parts/charm/build/staging-venv/bin/pip3 --version
pip 22.1 from /root/parts/charm/build/staging-venv/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by iknox-fa** [comment]
Thanks for diving in y'all. We're pinned to 22.0.4 for now.

**Comment by ptmcg** [comment]
New pip release will be out soon. https://github.com/pypa/pip/pull/11131

**Comment by ptmcg** [comment]
22.1.1 release should have addressed this - thanks for reporting!
