### ISSUE TITLE
Undocumented behavior: Keyword was immediately preceded by keyword character

### ISSUE THREAD

**Issue by grv87** [pyparsing/pyparsing#433]
```python
from pyparsing import *
s = "FOOBAR"
ast = Literal("FOO") + Keyword("BAR")
print(ast.parse_string(s))
```
gives
```
Traceback (most recent call last):
  File "…\pyparsing_spikes\issue_433.py", line 4, in <module>
    print(ast.parse_string(s))
  File "C:\root\Python\3.10\w64\lib\site-packages\pyparsing\core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected Keyword 'BAR', keyword was immediately preceded by keyword character, found 'OBAR'  (at char 2), (line:1, col:3)
```
Both [docstring](https://github.com/pyparsing/pyparsing/blob/06c12f685b5d0e29f01abc842dff8d268d93ffbf/pyparsing/core.py#L2452) and [online doc](https://pyparsing-docs.readthedocs.io/en/latest/HowToUsePyparsing.html#keyword) say about following characters, but don't say anything about preceding.

**Comment by grv87** [comment]
Also, this behavior is inconsistent with `Word` which doesn't check preceding characters.
```python
ast = Literal("FOO") + Word(alphanums)
print(ast.parse_string(s))
```
works.

**Comment by grv87** [comment]
> are not common keyword characters

The code uses `bodyChars`, not keyword characters.

> Word will by default match characters without checking for surrounding character matches

When length is not specified, then `Word` collects all characters while they match `bodyChars`. So, it checks the following characters. But not preceding.

I actually wanted to say that when the whole string is parsed, there is no sense to check what was before, since it had been parsed by some other parser already, and (since we continue), it was correct.
`Keyword` can't be used to check the end of keyword (starting with shared prefix). Looks like it can be worked around with `Literal` and `NotAny`. But length-less `Word` doesn't need this workaround.
