### ISSUE TITLE
Git master no longer compatible with Python 3.6

### ISSUE THREAD

**Issue by domdfcoding** [pyparsing/pyparsing#465]
The metadata in `pyproject.toml` specifies a minimum Python version of 3.6.8. However, 318ec7e3b945068d36f5c98b1de81003c773c6c4 added `from __future__ import annotations` to the top of `core.py`, which requires Python 3.7 or later. As a result pyparsing can't even be installed on Python 3.6:

```console
$ pip install git+https://github.com/pyparsing/pyparsing
Collecting git+https://github.com/pyparsing/pyparsing
  Cloning https://github.com/pyparsing/pyparsing to ./pip-req-build-5485bo08
  Running command git clone --filter=blob:none -q https://github.com/pyparsing/pyparsing /tmp/pip-req-build-5485bo08
  Resolved https://github.com/pyparsing/pyparsing to commit 14def7d7f454bfe891589a67801854b12e0b5ed2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/venv/bin/python3 /tmp/venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp3n097zvy
       cwd: /tmp/pip-req-build-5485bo08
  Complete output (23 lines):
  Traceback (most recent call last):
    File "/tmp/venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/tmp/venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-mj6t6arb/overlay/lib/python3.6/site-packages/flit_core/buildapi.py", line 49, in prepare_metadata_for_build_wheel
      metadata = make_metadata(module, ini_info)
    File "/tmp/pip-build-env-mj6t6arb/overlay/lib/python3.6/site-packages/flit_core/common.py", line 410, in make_metadata
      md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
    File "/tmp/pip-build-env-mj6t6arb/overlay/lib/python3.6/site-packages/flit_core/common.py", line 207, in get_info_from_module
      docstring, version = get_docstring_and_version_via_import(target)
    File "/tmp/pip-build-env-mj6t6arb/overlay/lib/python3.6/site-packages/flit_core/common.py", line 180, in get_docstring_and_version_via_import
      spec.loader.exec_module(m)
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/tmp/pip-req-build-5485bo08/pyparsing/__init__.py", line 132, in <module>
      from .core import __diag__, __compat__
    File "/tmp/pip-req-build-5485bo08/pyparsing/core.py", line 4
      from __future__ import annotations
      ^
  SyntaxError: future feature annotations is not defined
  ----------------------------------------
WARNING: Discarding git+https://github.com/pyparsing/pyparsing. Command errored out with exit status 1: /tmp/venv/bin/python3 /tmp/venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp3n097zvy Check the logs for full command output.
ERROR: Command errored out with exit status 1: /tmp/venv/bin/python3 /tmp/venv/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp3n097zvy Check the logs for full command output.
```

**Comment by ptmcg** [comment]
Thanks for reporting this - I'll get to it later today or this weekend.

I hope to push out 3.0.10 Very Soon Now.  As a "heads up", 3.1 will drop support for 3.6.
