### ISSUE TITLE
Ignoring character patterns

### ISSUE THREAD

**Issue by phobologic** [pyparsing/pyparsing#5]
Hi, I'm working on a better parser for a project that I run - the parser is for a templating language that allows a concept of "lookups" which will execute functions and replace the text with the results.  A lookup is in the form of: `${lookup_name lookup_values}` and they can be nested (you can provide a lookup as a lookup value).

I came up with the following use of pyparsing, but it fails on one of the test cases - largely because I feel like I'm missing something key to this kind of a parser.  Here's my code:

```
#!/usr/bin/python

from pyparsing import (
    CharsNotIn,
    Forward,
    OneOrMore,
    Suppress,
    White,
    Word,
    alphanums,
    alphas,
)


def build_parser():
    _open = "${"
    _close = "}"

    lookup = Forward()

    plain_string = CharsNotIn(_open + _close).setResultsName("contents")

    lookup_name = Word(alphas, alphanums + "_").setResultsName("name")
    lookup_input = OneOrMore(plain_string | lookup).setResultsName("contents")

    lookup << (
        Suppress(_open) + lookup_name + Suppress(OneOrMore(White(" ")))
        + OneOrMore(lookup_input) + Suppress(_close)
    )

    exp = OneOrMore(lookup | plain_string)

    return exp


if __name__ == '__main__':
    tests = [
        ("apple",
         "apple"),
        ("banana$apple",
         "banana$apple",),
        ("apple, apple, banana",
         "apple, apple, banana"),
    ]

    exp = build_parser()
    for t, expected in tests:
        r = exp.parseString(t)
        if not r.contents == expected:
            print "Failure:"
            print "  expected: %s" % expected
            print "    result: %s" % r.contents
```

And the output:

```
$ python test_parser.py
Failure:
  expected: banana$apple
    result: banana
```

Is there a better way of doing the:

```
plain_string = CharsNotIn(_open + _close).setResultsName("contents")
```

That only ignores strings that start with `${` and end with `}`?

Thanks!  And thanks for this awesome project!

**Comment by phobologic** [comment]
Also, if have any suggestsions on ways I can improve on the parser that I have here, please let me know!

**Comment by phobologic** [comment]
I've actually made some progress - using NotAny I'm able to get the correct value for `banana$apple`, but now that I've introduced a string matching a lookup, `${output MyStack::Output1}`, I'm now getting an error when parsing.

New code:

```
#!/usr/bin/python

from pyparsing import (
    Forward,
    NotAny,
    OneOrMore,
    Suppress,
    White,
    Word,
    alphanums,
    alphas,
    printables,
)


def build_parser():
    _open = "${"
    _close = "}"

    lookup = Forward()

    plain_string = OneOrMore(
        NotAny(_open) + NotAny(_close) + Word(printables)
    ).setResultsName("contents")

    lookup_name = Word(alphas, alphanums + "_").setResultsName("name")
    lookup_input = OneOrMore(lookup | plain_string).setResultsName("contents")

    lookup << (
        Suppress(_open) + lookup_name + Suppress(OneOrMore(White(" ")))
        + lookup_input + Suppress(_close)
    )

    exp = OneOrMore(lookup | plain_string)

    return exp


if __name__ == '__main__':
    tests = [
        ("apple",
         "apple"),
        ("banana$apple",
         "banana$apple",),
        ("apple, apple, banana",
         "apple, apple, banana"),
        ("${output MyStack::Output1}",
         "MyStack::Output1"),
    ]

    exp = build_parser()
    for t, expected in tests:
        r = exp.parseString(t)
        value = ' '.join(r.contents)
        if not value == expected:
            print "Failure:"
            print "  expected: %s (%s)" % (expected, type(expected))
            print "    result: %s (%s)" % (value, type(value))
```

Results:

```
# python ./simple_parsing2.py
Traceback (most recent call last):
  File "./simple_parsing2.py", line 53, in <module>
    r = exp.parseString(t)
  File "/Users/mike/venv/parsing/lib/python2.7/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
pyparsing.ParseException: Expected {Forward: ... | {{~{"${"} ~{"}"} W:(0123...)}}...} (at char 26), (line:1, col:27)
```

**Comment by ptmcg** [comment]
Sorry for not being more responsive - I am still in the process of my migration of this project to GitHub, so I'm not used to looking here for questions from users. Recursive grammars are tricky, you actually got pretty far on your own. I think the most concrete suggestions I have are:

- use the excludeChars arg for Word
- use Group to enclose nested lookups, to preserve nesting structure

The rest of these changes are mostly style, or personal habits I've developed along the way.

```
def build_parser():
    _open = Suppress("${")
    _close = Suppress("}")

    lookup = Forward()

    # excludeChars arg makes this simpler
    plain_string = Word(printables, excludeChars="${}")

    # don't put results names here - these low-level expressions might be used anywhere
    lookup_name = Word(alphas, alphanums + "_")
    lookup_input = OneOrMore(Group(lookup) | plain_string)

    # don't include White() when OneOrMore() is sufficient
    # I prefer the "expr('name')" style for setting parse results, and generally do it when
    # composing the next level 
    lookup << (_open + lookup_name("name") + lookup_input("contents") + _close)

    exp = OneOrMore(lookup | plain_string)

    return exp


if __name__ == '__main__':
    tests = [
        ("apple",
         "apple"),
        ("banana$apple",
         "banana$apple",),
        ("apple, apple, banana",
         "apple, apple, banana"),
        ("${output MyStack::Output1}",
         "MyStack::Output1"),
        ("${output MyStack::Output1 x}",
         "MyStack::Output1 x"),
        ("${output MyStack::Output1 ${another MyStack::Another}}",
         "MyStack::Output1 another MyStack::Another"),
    ]

    exp = build_parser()
    # consider using runTests() instead of writing your own testing code
    exp.runTests(t[0] for t in tests)
    
    for t, expected in tests:
        # echo the test input to simplify output
        print("\n" + t)
        r = exp.parseString(t)
        # dump() is handy for viewing the returned parse structure
        print(r.dump())
        value = ' '.join(r.contents)
        if not value == expected:
            print("Failure:")
            print("  expected: %s (%s)" % (expected, type(expected)))
            print("    result: %s (%s)" % (value, type(value)))
```

**Comment by ptmcg** [comment]
Yes, it is not working because we have excluded '$' as a valid character in `plain_string`.  You could get back '$' characters by creating a Combine of one or more words with no '$' with lone '$' characters. To guarantee that the '$' is not the leading character of a "${" group, use a negative lookahead:

    lone_dollar_sign = ~_open + "$"

Modify to read:

```
    string_with_no_dollar_sign = Word(printables, excludeChars="${}")
    lone_dollar_sign = ~_open + '$'
    plain_string = Combine(OneOrMore(string_with_no_dollar_sign | lone_dollar_sign))
```

What we are saying here is "combine one or more word groups that don't contain any '$' with consecutive lone '$' characters."

Combine ensures that we only match the contained expressions if there are no intervening spaces. It also merges all the matched parts into a single string.

**Comment by phobologic** [comment]
Wow, thanks so much @ptmcg - I think that entirely fixed my issue!  Sorry it's taken so long for me to get back to you, but I really really appreciate this, and I think the entire stacker (https://github.com/cloudtools/stacker) community will as well as I think this will make our configuration language so much better.

Thanks so much - I'll keep working on this!

**Comment by phobologic** [comment]
Ahhh - one last thing that is blocking me - is there anyway to keep track of spaces/make them important?  Here's my code right now (with stripped down tests to just show the issue I'm hitting):

```
from pyparsing import (
    Combine,
    Forward,
    OneOrMore,
    Group,
    Suppress,
    Word,
    alphanums,
    alphas,
    printables,
)


def build_parser():
    _open = Suppress("${")
    _close = Suppress("}")

    lookup = Forward()

    string_with_no_dollar_sign = Word(printables, excludeChars="${}")
    lone_dollar_sign = ~_open + '$'
    plain_string = Combine(
        OneOrMore(string_with_no_dollar_sign | lone_dollar_sign)
    )

    # don't put results names here - these low-level expressions might be used
    # anywhere
    lookup_name = Word(alphas, alphanums + "_")
    lookup_input = OneOrMore(Group(lookup) | plain_string)

    # don't include White() when OneOrMore() is sufficient
    # I prefer the "expr('name')" style for setting parse results, and
    # generally do it when composing the next level
    lookup << (
            _open +
            lookup_name("name") +
            lookup_input("contents") +
            _close
    )

    exp = OneOrMore(lookup | plain_string)

    return exp


if __name__ == '__main__':
    tests = [
        "${output MyStack::Output1}apple",
        "${output MyStack::Output1} apple",
    ]

    exp = build_parser()
    # consider using runTests() instead of writing your own testing code
    exp.runTests(tests)
```

When I run it, I get this:
```
${output MyStack::Output1}apple
['output', 'MyStack::Output1', 'apple']
- contents: ['MyStack::Output1']
- name: 'output'


${output MyStack::Output1} apple
['output', 'MyStack::Output1', 'apple']
- contents: ['MyStack::Output1']
- name: 'output'
```

As you can see, both of those look the same when parsed - even though the first version has no space between the lookup and the plain string, but the second does.  Any good way to handle this @ptmcg ?  Thanks again!

**Comment by phobologic** [comment]
Actually, I think I figured this out - digging in more, but this is looking good once again.  I'm going to close this - I'll open a new issue if I run into further confusion.  Thanks @ptmcg!
