### ISSUE TITLE
match_previous_expr does not handle nested expressions

### ISSUE THREAD

**Issue by ptmcg** [pyparsing/pyparsing#560]
See [this SO post](https://stackoverflow.com/questions/78574784/how-to-make-sure-element-has-parsing-precedence-before-other-elements-in-pyparsi), should be able to use match_previous_expr to enforce matching of opening and closing tags. Does not work for nested tags.

**Comment by Kaltxi** [comment]
I've tried some simpler expression grammars and even this doesn't work for me:
```python
import pyparsing as pp

LBRACE, RBRACE = map(pp.Suppress, "()")
NUMBER = pp.Word(pp.nums, pp.nums + ".")
MATH_TEXT = pp.Word("+-*/ ")

expression = pp.Forward()
GROUP = LBRACE + expression + RBRACE
expression = pp.OneOrMore(GROUP | NUMBER | MATH_TEXT)

print(expression.parse_string("5*(2+3)", parse_all=True).dump(" ")
```

This fails with an error:
```
Traceback (most recent call last):
  File "D:\pp-test\evaluation.py", line 119, in <module>
    print(expression.parse_string("5*(2+3)", parse_all=True).dump(" "))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python312\site-packages\pyparsing\core.py", line 1200, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '('  (at char 2), (line:1, col:3)
```

**Comment by ptmcg** [comment]
`expression = pp.OneOrMore(GROUP | NUMBER | MATH_TEXT)` should be `expression <<= pp.OneOrMore(GROUP | NUMBER | MATH_TEXT)`

**Comment by Kaltxi** [comment]
@ptmcg Right, thanks for pointing out! Basic nesting does work alright then.

**Comment by ptmcg** [comment]
Pyparsing supports some warnings to help in catching stuff like that. You have to enable them with -W switch or in code - see notes here: https://github.com/pyparsing/pyparsing/wiki/Parser-Debugging-and-Diagnostics#diagnostic-switches

**Comment by ptmcg** [comment]
Pyparsing has a helper method called `match_previous_expr()` that is intended for doing this kind of task, but it doesn't handle nested expression matching. That is, it could correctly validate `{tag1}some content{/tag1}`, but not `{tag1}some content{tag2}inner content{/tag2}{/tag1}`. I'll post a nested version here for you to try out - if it works for you, I'll include it in the next release.

**Comment by Kaltxi** [comment]
@ptmcg Hello! Sorry for the long delay, was working on other tasks. By the way, thanks for your work and attention to the project, pyparsing rocks, prototyping speed is very nice indeed :)

Now to the matter: yes, this looks nice and seems to work as intended. I even mananged to make a shorthand tag notation work (e.g. `{tag}Tagged{/t}`, but not `{tag}Tagged{/d}`):

``` python
LBRACE, RBRACE, SLASH = map(pp.Suppress, "{}/")
IDENTIFIER_CHARS = pp.alphanums + "_"

TAG_NAME_START = pp.Char(IDENTIFIER_CHARS)
TAG_NAME = pp.Word(IDENTIFIER_CHARS)

# Tags
OPEN_TAG = (
    LBRACE
    + pp.Group(pp.original_text_for((OPEN_TAG_NAME_START := TAG_NAME_START) + pp.Opt(TAG_NAME)))(
        "open_tag"
    )
    + RBRACE
)
CLOSE_TAG = (
    LBRACE
    + SLASH
    + pp.Group(
        pp.original_text_for(match_previous_expr_nested(OPEN_TAG_NAME_START) + pp.Opt(TAG_NAME))
    )("close_tag")
    + RBRACE
)

# Forward declaring content due to its recursivity
content = pp.Forward()
```

**Comment by rajeshkanade** [comment]
I looked into this and opened #653.

The cause is that `copy_token_to_repeater` calls `e2.add_parse_action(...)` on every match of the
leading expression and never removes one, so after N matches all N guards run on each attempt to
match the repeat and at most one of them can succeed.

It turns out to be a bit wider than nesting. A second pair anywhere in the input fails too — `a:a b:b`
under `OneOrMore` doesn't parse — and once a parse has failed, the same expression keeps rejecting
valid input, because the stale guard is still attached.

Your `match_previous_expr_nested` from June 2024 handles the nesting cases. When I ran it against the
current test suite it regressed `testRepeaterPreservesParseAction` and
`testRepeaterRecursiveWhitespace`, because `set_parse_action` replaces the parse actions the copied
expression already carries — `ppc.integer`'s int conversion gets dropped. Registering the guard once
at construction with `add_parse_action` and keeping the pending matches on a stack avoids that.

I put the fix in `match_previous_expr` itself rather than adding a second helper, since CONTRIBUTING
asks to minimise additions to the namespace and I couldn't find existing behaviour that changes other
than the bug. Happy to split it into a separate `match_previous_expr_nested` if you'd rather keep the
current semantics untouched.

**Comment by ptmcg** [comment]
Updating `match_previous_expr()` was the right call.
