### ISSUE TITLE
import error sklearn

### ISSUE THREAD

**Issue by VaibhavSxn** [pyparsing/pyparsing#81]
Hello I am trying to import train_test_split module from sklearn and I am getting list index out of range error.

Below is  my code:
import sklearn
from sklearn import model_selection
from sklearn.model_selection import train_test_split

Below is the error:
from sklearn import model_selection
Traceback (most recent call last):

  File "<ipython-input-106-97adc105df53>", line 1, in <module>
    from sklearn import model_selection

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\sklearn\model_selection\__init__.py", line 19, in <module>
    from ._validation import cross_val_score

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 31, in <module>
    from ..metrics.scorer import check_scoring, _check_multimetric_scoring

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\sklearn\metrics\__init__.py", line 7, in <module>
    from .ranking import auc

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\sklearn\metrics\ranking.py", line 36, in <module>
    from ..preprocessing import label_binarize

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\sklearn\preprocessing\__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\sklearn\preprocessing\_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\sklearn\utils\testing.py", line 63, in <module>
    from nose.tools import raises as _nose_raises

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\nose\__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\nose\core.py", line 11, in <module>
    from nose.config import Config, all_config_files

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\nose\config.py", line 8, in <module>
    from nose.util import absdir, tolist

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\nose\util.py", line 12, in <module>
    from nose.pyversion import ClassType, TypeType, isgenerator, ismethod

  File "C:\Users\gunngunner\Anaconda3\lib\site-packages\nose\pyversion.py", line 36, in <module>
    import new

  File "C:\Users\gunngunner\new.py", line 6, in <module>
    if a[item]%2 != 0:

IndexError: list index out of range

**Comment by ptmcg** [comment]
Is this a pyparsing-related question?
